package jp.fores.gruul.db.entity;

import java.util.Date;

public class IGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.name
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.owner_user_uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String ownerUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.expire_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date expireAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.latitude
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Long latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.longitude
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Long longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.comment
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.opened_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date openedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.deleted_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.created_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_group.updated_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public IGroup(Integer id, String uuid, String name, String ownerUserUuid, Date expireAt, Long latitude, Long longitude, String comment, Date openedAt, Date deletedAt, Date createdAt, Date updatedAt) {
        this.id = id;
        this.uuid = uuid;
        this.name = name;
        this.ownerUserUuid = ownerUserUuid;
        this.expireAt = expireAt;
        this.latitude = latitude;
        this.longitude = longitude;
        this.comment = comment;
        this.openedAt = openedAt;
        this.deletedAt = deletedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.id
     *
     * @return the value of i_group.id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.uuid
     *
     * @return the value of i_group.uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.name
     *
     * @return the value of i_group.name
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.owner_user_uuid
     *
     * @return the value of i_group.owner_user_uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getOwnerUserUuid() {
        return ownerUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.expire_at
     *
     * @return the value of i_group.expire_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getExpireAt() {
        return expireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.latitude
     *
     * @return the value of i_group.latitude
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Long getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.longitude
     *
     * @return the value of i_group.longitude
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Long getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.comment
     *
     * @return the value of i_group.comment
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.opened_at
     *
     * @return the value of i_group.opened_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getOpenedAt() {
        return openedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.deleted_at
     *
     * @return the value of i_group.deleted_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.created_at
     *
     * @return the value of i_group.created_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_group.updated_at
     *
     * @return the value of i_group.updated_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }
}