package jp.fores.gruul.db.entity;

import java.util.Date;

public class IUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.nickname
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.icon_id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String iconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.icon_path
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String iconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.type
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.device_token
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.notification
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Boolean notification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.deleted_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.created_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.updated_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public IUser(Integer id, String uuid, String nickname, String iconId, String iconPath, Short type, String deviceToken, Boolean notification, Date deletedAt, Date createdAt, Date updatedAt) {
        this.id = id;
        this.uuid = uuid;
        this.nickname = nickname;
        this.iconId = iconId;
        this.iconPath = iconPath;
        this.type = type;
        this.deviceToken = deviceToken;
        this.notification = notification;
        this.deletedAt = deletedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.id
     *
     * @return the value of i_user.id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.uuid
     *
     * @return the value of i_user.uuid
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.nickname
     *
     * @return the value of i_user.nickname
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.icon_id
     *
     * @return the value of i_user.icon_id
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.icon_path
     *
     * @return the value of i_user.icon_path
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.type
     *
     * @return the value of i_user.type
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.device_token
     *
     * @return the value of i_user.device_token
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.notification
     *
     * @return the value of i_user.notification
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Boolean getNotification() {
        return notification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.deleted_at
     *
     * @return the value of i_user.deleted_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.created_at
     *
     * @return the value of i_user.created_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.updated_at
     *
     * @return the value of i_user.updated_at
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }
}