package jp.fores.gruul.db.map;

import java.util.Date;
import java.util.List;
import jp.fores.gruul.db.entity.IGroup;
import jp.fores.gruul.db.entity.IGroupExample;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IGroupSqlProvider.class, method="countByExample")
    int countByExample(IGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @DeleteProvider(type=IGroupSqlProvider.class, method="deleteByExample")
    int deleteByExample(IGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Delete({
        "delete from i_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Insert({
        "insert into i_group (id, uuid, ",
        "name, owner_user_uuid, ",
        "expire_at, latitude, ",
        "longitude, comment, ",
        "opened_at, deleted_at, ",
        "created_at, updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{uuid,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{ownerUserUuid,jdbcType=VARCHAR}, ",
        "#{expireAt,jdbcType=TIMESTAMP}, #{latitude,jdbcType=BIGINT}, ",
        "#{longitude,jdbcType=BIGINT}, #{comment,jdbcType=VARCHAR}, ",
        "#{openedAt,jdbcType=TIMESTAMP}, #{deletedAt,jdbcType=TIMESTAMP}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(IGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @InsertProvider(type=IGroupSqlProvider.class, method="insertSelective")
    int insertSelective(IGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IGroupSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="owner_user_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="expire_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="latitude", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="longitude", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="comment", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="opened_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<IGroup> selectByExample(IGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Select({
        "select",
        "id, uuid, name, owner_user_uuid, expire_at, latitude, longitude, comment, opened_at, ",
        "deleted_at, created_at, updated_at",
        "from i_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="owner_user_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="expire_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="latitude", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="longitude", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="comment", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="opened_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    IGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IGroupSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IGroup record, @Param("example") IGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IGroupSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IGroup record, @Param("example") IGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IGroupSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Update({
        "update i_group",
        "set uuid = #{uuid,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "owner_user_uuid = #{ownerUserUuid,jdbcType=VARCHAR},",
          "expire_at = #{expireAt,jdbcType=TIMESTAMP},",
          "latitude = #{latitude,jdbcType=BIGINT},",
          "longitude = #{longitude,jdbcType=BIGINT},",
          "comment = #{comment,jdbcType=VARCHAR},",
          "opened_at = #{openedAt,jdbcType=TIMESTAMP},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IGroup record);
}