package jp.fores.gruul.db.map;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import jp.fores.gruul.db.entity.IUserGroup;
import jp.fores.gruul.db.entity.IUserGroupExample.Criteria;
import jp.fores.gruul.db.entity.IUserGroupExample.Criterion;
import jp.fores.gruul.db.entity.IUserGroupExample;

public class IUserGroupSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String countByExample(IUserGroupExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("i_user_group");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String deleteByExample(IUserGroupExample example) {
        BEGIN();
        DELETE_FROM("i_user_group");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String insertSelective(IUserGroup record) {
        BEGIN();
        INSERT_INTO("i_user_group");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGroupUuid() != null) {
            VALUES("group_uuid", "#{groupUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            VALUES("user_uuid", "#{userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getJoined() != null) {
            VALUES("joined", "#{joined,jdbcType=BIT}");
        }
        
        if (record.getRemoved() != null) {
            VALUES("removed", "#{removed,jdbcType=BIT}");
        }
        
        if (record.getArrived() != null) {
            VALUES("arrived", "#{arrived,jdbcType=BIT}");
        }
        
        if (record.getComment() != null) {
            VALUES("comment", "#{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getDeletedAt() != null) {
            VALUES("deleted_at", "#{deletedAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreatedAt() != null) {
            VALUES("created_at", "#{createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedAt() != null) {
            VALUES("updated_at", "#{updatedAt,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String selectByExample(IUserGroupExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("group_uuid");
        SELECT("user_uuid");
        SELECT("joined");
        SELECT("removed");
        SELECT("arrived");
        SELECT("comment");
        SELECT("deleted_at");
        SELECT("created_at");
        SELECT("updated_at");
        FROM("i_user_group");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        IUserGroup record = (IUserGroup) parameter.get("record");
        IUserGroupExample example = (IUserGroupExample) parameter.get("example");
        
        BEGIN();
        UPDATE("i_user_group");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getGroupUuid() != null) {
            SET("group_uuid = #{record.groupUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getJoined() != null) {
            SET("joined = #{record.joined,jdbcType=BIT}");
        }
        
        if (record.getRemoved() != null) {
            SET("removed = #{record.removed,jdbcType=BIT}");
        }
        
        if (record.getArrived() != null) {
            SET("arrived = #{record.arrived,jdbcType=BIT}");
        }
        
        if (record.getComment() != null) {
            SET("comment = #{record.comment,jdbcType=VARCHAR}");
        }
        
        if (record.getDeletedAt() != null) {
            SET("deleted_at = #{record.deletedAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreatedAt() != null) {
            SET("created_at = #{record.createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedAt() != null) {
            SET("updated_at = #{record.updatedAt,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("i_user_group");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("group_uuid = #{record.groupUuid,jdbcType=VARCHAR}");
        SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        SET("joined = #{record.joined,jdbcType=BIT}");
        SET("removed = #{record.removed,jdbcType=BIT}");
        SET("arrived = #{record.arrived,jdbcType=BIT}");
        SET("comment = #{record.comment,jdbcType=VARCHAR}");
        SET("deleted_at = #{record.deletedAt,jdbcType=TIMESTAMP}");
        SET("created_at = #{record.createdAt,jdbcType=TIMESTAMP}");
        SET("updated_at = #{record.updatedAt,jdbcType=TIMESTAMP}");
        
        IUserGroupExample example = (IUserGroupExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    public String updateByPrimaryKeySelective(IUserGroup record) {
        BEGIN();
        UPDATE("i_user_group");
        
        if (record.getGroupUuid() != null) {
            SET("group_uuid = #{groupUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            SET("user_uuid = #{userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getJoined() != null) {
            SET("joined = #{joined,jdbcType=BIT}");
        }
        
        if (record.getRemoved() != null) {
            SET("removed = #{removed,jdbcType=BIT}");
        }
        
        if (record.getArrived() != null) {
            SET("arrived = #{arrived,jdbcType=BIT}");
        }
        
        if (record.getComment() != null) {
            SET("comment = #{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getDeletedAt() != null) {
            SET("deleted_at = #{deletedAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreatedAt() != null) {
            SET("created_at = #{createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedAt() != null) {
            SET("updated_at = #{updatedAt,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    protected void applyWhere(IUserGroupExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}