package jp.fores.gruul.db.map;

import java.util.Date;
import java.util.List;
import jp.fores.gruul.db.entity.IUserGroup;
import jp.fores.gruul.db.entity.IUserGroupExample;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IUserGroupSqlProvider.class, method="countByExample")
    int countByExample(IUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @DeleteProvider(type=IUserGroupSqlProvider.class, method="deleteByExample")
    int deleteByExample(IUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Delete({
        "delete from i_user_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Insert({
        "insert into i_user_group (id, group_uuid, ",
        "user_uuid, joined, removed, ",
        "arrived, comment, deleted_at, ",
        "created_at, updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{groupUuid,jdbcType=VARCHAR}, ",
        "#{userUuid,jdbcType=VARCHAR}, #{joined,jdbcType=BIT}, #{removed,jdbcType=BIT}, ",
        "#{arrived,jdbcType=BIT}, #{comment,jdbcType=VARCHAR}, #{deletedAt,jdbcType=TIMESTAMP}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(IUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @InsertProvider(type=IUserGroupSqlProvider.class, method="insertSelective")
    int insertSelective(IUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IUserGroupSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="group_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="user_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="joined", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="removed", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="arrived", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="comment", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<IUserGroup> selectByExample(IUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Select({
        "select",
        "id, group_uuid, user_uuid, joined, removed, arrived, comment, deleted_at, created_at, ",
        "updated_at",
        "from i_user_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="group_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="user_uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="joined", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="removed", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="arrived", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="comment", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    IUserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserGroupSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IUserGroup record, @Param("example") IUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserGroupSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IUserGroup record, @Param("example") IUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserGroupSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_group
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Update({
        "update i_user_group",
        "set group_uuid = #{groupUuid,jdbcType=VARCHAR},",
          "user_uuid = #{userUuid,jdbcType=VARCHAR},",
          "joined = #{joined,jdbcType=BIT},",
          "removed = #{removed,jdbcType=BIT},",
          "arrived = #{arrived,jdbcType=BIT},",
          "comment = #{comment,jdbcType=VARCHAR},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IUserGroup record);
}