package jp.fores.gruul.db.map;

import java.util.Date;
import java.util.List;
import jp.fores.gruul.db.entity.IUser;
import jp.fores.gruul.db.entity.IUserExample;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IUserSqlProvider.class, method="countByExample")
    int countByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @DeleteProvider(type=IUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Delete({
        "delete from i_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Insert({
        "insert into i_user (id, uuid, ",
        "nickname, icon_id, ",
        "icon_path, type, ",
        "device_token, notification, ",
        "deleted_at, created_at, ",
        "updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{uuid,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{iconId,jdbcType=VARCHAR}, ",
        "#{iconPath,jdbcType=VARCHAR}, #{type,jdbcType=SMALLINT}, ",
        "#{deviceToken,jdbcType=VARCHAR}, #{notification,jdbcType=BIT}, ",
        "#{deletedAt,jdbcType=TIMESTAMP}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @InsertProvider(type=IUserSqlProvider.class, method="insertSelective")
    int insertSelective(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @SelectProvider(type=IUserSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="nickname", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="icon_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="icon_path", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="device_token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="notification", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<IUser> selectByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Select({
        "select",
        "id, uuid, nickname, icon_id, icon_path, type, device_token, notification, deleted_at, ",
        "created_at, updated_at",
        "from i_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="uuid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="nickname", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="icon_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="icon_path", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="device_token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="notification", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="deleted_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="created_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updated_at", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    IUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IUser record, @Param("example") IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IUser record, @Param("example") IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @UpdateProvider(type=IUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 18 16:00:43 JST 2014
     */
    @Update({
        "update i_user",
        "set uuid = #{uuid,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "icon_id = #{iconId,jdbcType=VARCHAR},",
          "icon_path = #{iconPath,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=SMALLINT},",
          "device_token = #{deviceToken,jdbcType=VARCHAR},",
          "notification = #{notification,jdbcType=BIT},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IUser record);
}